language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# script to run tests
script:
  # nosetest
  # nosetests --with-coverage --cover-erase --cover-inclusive --cover-package=app
  # pytest
   py.test --cov-report term --cov=app flaskapp/test/test_models.py
after_success:
   coveralls
notifications:
  # don't send email for succeful and unsuccessful builds
  